openapi: 3.0.0
info:
  title: MyService API
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  /ip:
    get:
      operationId: getIpAddress
      summary: Get IP Address
      responses:
        '200':
          description: OK
  /addr:
    get:
      operationId: getAddress
      summary: Get Address
      responses:
        '426':
          description: HTTPS Upgrade Required
      servers:
        - url: https://{proxyHost}
          variables:
            proxyHost:
              description: The host of the proxy server
              default: httpbin.org
              enum:
                - httpbin.org
