openapi: "3.0.0"
info:
  title: "API"
  version: "1.0.0"
  contact:
    name: "Your Name"
    email: "your.email@example.com"
  description: "API description"
servers:
  - url: "https://httpbin.org"
paths:
  /ip:
    get:
      summary: "Get IP address"
      tags:
        - "IP"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
        '429':
          description: "Rate limit exceeded"
      x-rate-limit:
        description: "Rate limit settings"
        type: object
        properties:
          minute:
            type: integer
            example: 2
          fault_tolerant:
            type: boolean
            example: true
        required:
          - minute
          - fault_tolerant
      security:
        - api_key: []
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-Key
      in: header
