openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
servers:
  - url: http://mockbintareget.apigee.net
paths:
  /users:
    get:
      summary: Retrieve user data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
components:
  schemas:
    UsersResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
