name: Demo # Specify the name of the deploymen

on:
  push:
    branches:
      - main  # Trigger the deployment when pushing to the main branch

jobs:
  enable-registration-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Application Registration plugin for multiple services
        run: |
          SERVICES=("MyService_API:622bb470-d93c-4c70-8b09-6c1bb8389c1b")
          for SERVICE in "${SERVICES[@]}"
          do
            SERVICE_NAME=$(echo $SERVICE | cut -d':' -f1)
            SERVICE_ID=$(echo $SERVICE | cut -d':' -f2)
            PAYLOAD=$(echo "{\"name\": \"application-registration\", \"config\": {\"auto_approve\": false, \"description\": \"any discription\", \"display_name\": \"${SERVICE_NAME}\"}}")
            curl -X POST https://ec2-34-217-81-88.us-west-2.compute.amazonaws.com:8444/services/${SERVICE_NAME}|${SERVICE_ID}/plugins -d "$PAYLOAD" -k
          done
