name: Demo to Delpoy OAS to Kong # Specify the name of the deployment

on:
  push:
    branches:
      - main  # Trigger the deployment when pushing to the main branch

jobs:
  OAS_To_KONG:
    runs-on: ubuntu-latest  # Use Ubuntu as the operating system for the job

    steps:
    - name: Checkout Code  # Checkout the code from the repository
      uses: actions/checkout@v2

    - name: Install Insomnia CLI  # Install Insomnia CLI for linting and generating Kong configuration
      run: |
         wget https://github.com/Kong/insomnia/releases/download/lib%403.14.0/inso-linux-3.14.0.tar.xz
         tar -xf inso-linux-3.14.0.tar.xz

    - name: Lint OpenAPI Spec  # Lint the OpenAPI spec using Insomnia CLI
      run: ./inso lint spec apiops.yaml
    - name: Generate kong.yaml  # Generate Kong configuration in declarative format
      run: ./inso generate config apiops.yaml --type declarative -o kong_gen.yaml --kongVersion 3.0
    - name: open kong.yaml  # Display the contents of the generated Kong configuration
      run: cat /home/runner/work/GitHubActionsDemo/GitHubActionsDemo/kong_gen.yaml
    - name: install deck CLI  # Install deck CLI for syncing Kong configuration
      run: |
        curl -sL https://github.com/kong/deck/releases/download/v1.17.2/deck_1.17.2_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp 
        sudo cp /tmp/deck /usr/local/bin/

    - name: check  # Validate the Kong configuration using deck CLI
      run: deck validate -s /home/runner/work/GitHubActionsDemo/GitHubActionsDemo/kong_gen.yaml

    - name: Deploy to Kong  # Sync the Kong configuration to Kong API Gateway
      run: deck sync -s kong_gen.yaml --kong-addr ${{ secrets.KONG_ADMIN_ADDR }} --tls-skip-verify
  publish-customer-api-to-portal:  # Publish the API to the dev portal
    name: Publish OAS to dev portal
    needs: OAS_To_KONG  # Make sure the OAS_To_KONG job is completed before running this job
    runs-on: ubuntu-latest  # Use Ubuntu as the operating system for the job
    steps:
      - name: Checkout branch  # Checkout the branch from the repository
        uses: actions/checkout@v2
      - name: Install NodeJs  # Install Node.js for running the dev portal CLI
        uses: actions/setup-node@v3
      - name: Install kon-dev-portal-cli  # Install dev portal CLI
        run: npm install -g kong-portal-cli
      - name: Deploy to dev portal
        run: |          
          portal deploy --preserve default -D
        env:
          KONG_ADMIN_URL: ${{ secrets.KONG_ADMIN_ADDR }}
